cloud:
  aws:
    credentials:
      accessKey: AKIAZJHGNPP23ULU6H73
      secretKey: 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
      instanceProfile : true
    s3:
      bucket: gotgam
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

