cloud:
  aws:
    credentials:
      accessKey: AKIASP764BG4AEOKN3NZ
      secretKey: 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
      instanceProfile : true
    s3:
      bucket: mulmul
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB